import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/global/Footer";

import ToasterProvider from "@/components/providers/ToasterProvider";
import RegenerateModal from "@/components/modal/RegenerateModal";
import { Suspense } from "react";
import { getServerSession } from "next-auth";
import { options } from "./api/auth/[...nextauth]/options";

export const metadata: Metadata = {
  title: "ACM Curation Tool",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(options);
  return (
    <html lang="en">
      <body
        className="flex min-h-screen flex-col"
        suppressHydrationWarning={true}>
        <ToasterProvider />
        <RegenerateModal />
        {/* <NetworkModal /> */}
        {session && <Navbar user={session?.user} />}
        <Suspense>
          <main className="flex-grow">{children}</main>
        </Suspense>
        {session && <Footer />}
      </body>
    </html>
  );
}
