import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/global/Footer";
import NetworkModal from "@/components/modal/NetworkModal";
import ToasterProvider from "@/components/providers/ToasterProvider";
import EditorContextProvider from "@/components/editor/EditorContext";

export const metadata: Metadata = {
  title: "ACM Curation Tool",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="flex min-h-screen flex-col"
        suppressHydrationWarning={true}>
        <ToasterProvider />
        <NetworkModal />
        <Navbar />
        <EditorContextProvider>
          <main className="flex-grow">{children}</main>
        </EditorContextProvider>
        <Footer />
      </body>
    </html>
  );
}
